<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPT73glX\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPT73glX/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPT73glX.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerPT73glX\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerPT73glX\srcProdProjectContainer(array(
    'container.build_hash' => 'PT73glX',
    'container.build_id' => '6b2456f8',
    'container.build_time' => 1521938341,
));
