<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXwtgd74\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXwtgd74/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXwtgd74.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXwtgd74\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXwtgd74\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Xwtgd74',
    'container.build_id' => '543377ed',
    'container.build_time' => 1521938108,
));
